version: 1.0.0
created_at: '2025-09-05T20:50:00.000000'
modified_at: '2025-09-05T20:50:00.000000'

processing:
  target_fps: 30.0
  frame_skip: 1
  resize_width: 640
  resize_height: 480
  parallel_processing: true
  max_workers: 4
  gpu_enabled: true
  gpu_memory_limit: null

output:
  formats: ["JSON", "CSV", "EXCEL"]
  output_directory: results
  create_timestamp_folder: true
  detailed_timeline: true
  include_confidence_scores: true
  export_visualizations: false

phase_detection:
  sequence_length: 30
  overlap_threshold: 0.7
  temporal_smoothing: true
  smoothing_window: 5
  min_phase_duration: 2.0
  transition_buffer: 0.5

instrument_tracking:
  max_tracked_objects: 10
  tracking_confidence_threshold: 0.3
  nms_threshold: 0.5
  track_buffer: 30
  match_threshold: 0.8
  usage_timeline_enabled: true

event_detection:
  bleeding_detection_threshold: 0.4
  suture_attempt_threshold: 0.5
  anchor_event_threshold: 0.6
  event_clustering_enabled: true
  clustering_time_window: 2.0
  min_event_duration: 0.5

motion_analysis:
  motion_threshold_low: 0.1
  motion_threshold_high: 0.3
  idle_threshold_short: 3.0
  idle_threshold_long: 10.0
  instrument_confidence_threshold: 0.3
  optical_flow_enabled: true
  smoothing_window: 5

models:
  phase_detector:
    model_type: "PHASE_DETECTION"
    model_path: "phase_detector.pth"
    enabled: true
    confidence_threshold: 0.5
    batch_size: 32
    custom_parameters: {}
    
  instrument_tracker:
    model_type: "INSTRUMENT_TRACKING"
    model_path: "instrument_tracker.pth"
    enabled: true
    confidence_threshold: 0.5
    batch_size: 32
    custom_parameters: {}
    
  event_detector:
    model_type: "EVENT_DETECTION"
    model_path: "event_detector.pth"
    enabled: true
    confidence_threshold: 0.5
    batch_size: 32
    custom_parameters: {}
    
  motion_analyzer:
    model_type: "MOTION_ANALYSIS"
    model_path: "motion_analyzer.pth"
    enabled: true
    confidence_threshold: 0.5
    batch_size: 32
    custom_parameters: {}

logging_level: INFO
enable_profiling: false
cache_enabled: true
cache_size_mb: 512